### ISSUE TITLE
Many entries are missing in the gtk file chooser

### ISSUE THREAD

**Issue by glaubersm** [flathub/org.gnome.Rhythmbox3#13]
Hi
I use Arch Linux, Gnome 3.28.2, flatpak 0.99.3-1.
First screenshot shows the player installed from Arch Linux repositories, second screenshot shows the flatpak version. In flatpak version, several entries are missing in the sidebar (bookmarks and some default entries). Also additional hard disk partitions and samba shares are not avaiable under "outros locais" (other locations).

![player arch](https://user-images.githubusercontent.com/15967631/42729850-27ae7a04-87bc-11e8-8b58-8169718b2ec1.png)

![player flatpak](https://user-images.githubusercontent.com/15967631/42729851-2d493738-87bc-11e8-97e8-3137a8258ef4.png)

**Comment by TingPing** [comment]
It is running in the sandbox so yea. Rhythmbox upstream needs to be ported to GtkFileChooserNative which is something to report to them.

**Comment by glaubersm** [comment]
https://gitlab.gnome.org/GNOME/rhythmbox/issues/1647

**Comment by antistress** [comment]
I can confirm this bug report on my Debian Sid 64 bits with GNOME-X11

Rhythmbox 3.4.3 from flathub shows my Music dir unlike any other of my xdg-user-dirs
Rhythmbox 3.4.3-2 from debian-testing-main shows all my xdg-user-dirs
 
I've written it on https://gitlab.gnome.org/GNOME/rhythmbox/issues/1647

Thanks
