### ISSUE TITLE
Unable to set network share as music source

### ISSUE THREAD

**Issue by unholyeyebrows** [flathub/org.gnome.Rhythmbox3#14]
Testing on Fedora 28 & Fedora 29 Silverblue. Both have same symptoms. Rhythmbox3 installed from flathub and up to date.

I store my music on an NFS share which I have mounted via autofs into /var/mnt/music
In turn, I have a symlink to this into my ~/Music folder thus:
ln -s /var/mnt/music/MP3/ Music/
When running Rhythmbox from standard rpm I am able to use this as my library folder and therefore play my music straight off my file server. However the flatpak version of Rhythmbox does not allow me access to this.

Here's how I duplicate the issue:
Launch Rhythmbox, go to Preferences -> Music -> Library location
Us the file browser to enter my Music folder. Here, I can see my MP3 symlink but it appears like a text file and is greyed out. Instead I would expect this to appear like a folder which I can select for my library.
![screenshot from 2018-09-17 11-04-07](https://user-images.githubusercontent.com/11313997/45617205-790c9400-ba69-11e8-9874-4516a5d7eacb.png)

**Comment by hadess** [comment]
I think this is fixed since commit a1a94287c17c00027ca100d30a542b530b675c2b, could you please check whether this is still a problem after upgrading?

**Comment by hadess** [comment]
Been 5 months without an answer, closing.

**Comment by goncalossilva** [comment]
Just installed Rhythmbox via Flathub, and have the same exact problem on version 3.4.4.

I can't access my collection in the network share (nfs). The symlink trick is neat but also fails, appearing greyed out:

![nope](https://cl.ly/00698fe2005c/gnome-shell-screenshot-XENSF0.png)

**Comment by hadess** [comment]
The fact that it doesn't follow symbolic links is a security feature. There's currently no support for native network shares in the portals, so we can't implement support for them in Rhythmbox.

We do however already support network shares handled through gvfs, so you should be able to mount your NFS/SMB/etc. share using the `gio` command-line tool or a file manager like nautilus, and access all the files there.

**Comment by unholyeyebrows** [comment]
Hi - just to wrap this up from my side, I stopped using autofs and started mounting my shares via SAMBA and Gnome Nautilus and have Rhythmbox accessing my NAS-hosted music fine as a result. Thanks, Nick
