### ISSUE TITLE
Package Alternate toolbar plugin

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.gnome.Rhythmbox3#2]
The alternate toolbar plugin allows for Rhythmbox to use Gtk Header bars, this allows for the user to change the interface to something which may look more 'native' on their desktop.

**Comment by jmatthew** [comment]
I'm not going to include any out-of-tree plugins.

**Comment by ahayzen** [comment]
Fair enough :-) I wonder if Rhythmbox should take part in the CSD initiative https://wiki.gnome.org/Initiatives/CSD ?
