### ISSUE TITLE
Can't import my music which is located in /mnt/

### ISSUE THREAD

**Issue by antistress** [flathub/org.gnome.Rhythmbox3#20]
On my Debian Sid 64 bits with GNOME-X11, I can't import my music which is located in /mnt/

Indeed I have changed default xdg-user-dirs in ~/.config/user-dirs.dirs : my xdg-user-dirs are located in /mnt/ – for instance XDG_MUSIC_DIR is /mnt/data/Music (/mnt/data/ is on a second drive)

To be clear I see 2 problems : I can't import my music since xdg-user-dirs are not displayed and since GTK File Chooser within Rhythmbox doesn't allow me to browse /mnt/ directory which is not displayed either

Thanks

**Comment by antistress** [comment]
Not sure if this bug is related to/duplicate of bug #14 ?

**Comment by hadess** [comment]
The json file has `"--filesystem=xdg-music"`, but I'm pretty sure it expects xdg-music to be inside `/home`.

This would be a bug against Flatpak itself, which you can file at https://github.com/flatpak/flatpak/issues

Given that Rhythmbox gets access to xdg-music when it's in the local home dir, I'll close this as a Flatpak bug. Please tell us the issue number once you've filed it, or CC: me on it.

**Comment by antistress** [comment]
Hi,
Corresponding flatpak bug is https://github.com/flatpak/flatpak/issues/2949
Thanks

**Comment by antistress** [comment]
I'd like to apologize since this isn't a bug 

I've checked my ~/.config/user-dirs.dirs and it seems it has been reset
Once my ~/.config/user-dirs.dirs restored, I can access to XDG_MUSIC_DIR

The only remaining bug for me is : "[flatpak] Several entries are missing in the gtk file chooser" which has been reported at https://gitlab.gnome.org/GNOME/rhythmbox/issues/1647

This bug can be closed

Sorry again for the annoyance

Thanks
