### ISSUE TITLE
Cannot add to playlist with drag and drop when file is outside ~/Music

### ISSUE THREAD

**Issue by ThanosApostolou** [flathub/org.gnome.Rhythmbox3#21]
I have most of my music in a separate partition and I cannot drag and drop a file in the Music when it is outside from my ~/Music folder. When I drag and drop it I see the "Adding tracks to the library" notice but the song isn't getting added. Opening the file with rhythmbox works but I don't want it because it changes the current playing song. Oddly enough, it works fine with every music files that I have in my mounted samba share.

Problem doesn't exist in Fedora 30 package so it must be flatpak specific.

**Comment by TingPing** [comment]
https://github.com/flatpak/xdg-desktop-portal/issues/99

**Comment by svastian99** [comment]
The app works well with music files on Linux partitions ... but  does not allow me to add music to the library from NTFS partitions.
