### ISSUE TITLE
Crash when indexing music

### ISSUE THREAD

**Issue by felipehw** [flathub/org.gnome.Rhythmbox3#28]
Hi.
My Rhythmbox crashes only at the Flatpak version.
The crash occurs when it is indexing my music. When I open it again, it restarts the indexing and crashes again.

CLI of crashing:
```
$ flatpak run org.gnome.Rhythmbox3
Gtk-Message: 17:49:07.262: Failed to load module "pk-gtk-module"
Gtk-Message: 17:49:07.263: Failed to load module "pk-gtk-module"
Gtk-Message: 17:49:24.725: Failed to load module "pk-gtk-module"
Gtk-Message: 17:49:24.727: Failed to load module "pk-gtk-module"
Gtk-Message: 17:49:24.993: Failed to load module "pk-gtk-module"
Gtk-Message: 17:49:24.994: Failed to load module "pk-gtk-module"
Recursion depth exceeded calculating bg color
Recursion depth exceeded calculating fg color
Recursion depth exceeded calculating fg color
Recursion depth exceeded calculating bg color
Recursion depth exceeded calculating bg color
Recursion depth exceeded calculating fg color
Recursion depth exceeded calculating fg color
Recursion depth exceeded calculating fg color
Recursion depth exceeded calculating fg color
Recursion depth exceeded calculating fg color
Recursion depth exceeded calculating fg color
Recursion depth exceeded calculating bg color
Recursion depth exceeded calculating bg color
Recursion depth exceeded calculating bg color
Recursion depth exceeded calculating bg color
Recursion depth exceeded calculating bg color

(rhythmbox-metadata:17): GStreamer-WARNING **: 17:51:10.518: Trying to set string on taglist field 'title', but string is not valid UTF-8. Please file a bug.

(rhythmbox-metadata:17): GStreamer-WARNING **: 17:51:10.674: Trying to set string on taglist field 'title', but string is not valid UTF-8. Please file a bug.

(rhythmbox-metadata:17): GStreamer-WARNING **: 17:51:10.744: Trying to set string on taglist field 'title', but string is not valid UTF-8. Please file a bug.

** (process:588604): WARNING **: 17:53:00.998: Invalid message header format

(rhythmbox:2): Rhythmbox-WARNING **: 17:53:00.998: Unable to emit Updated signal for MediaServer2 container /org/gnome/UPnP/MediaServer2/Library/all: The connection is closed

(rhythmbox:2): Rhythmbox-WARNING **: 17:53:00.998: Unable to send property changes for MediaServer2 container /org/gnome/UPnP/MediaServer2/Playlists/94020775335104: The connection is closed

(rhythmbox:2): Rhythmbox-WARNING **: 17:53:00.998: Unable to emit Updated signal for MediaServer2 container /org/gnome/UPnP/MediaServer2/Playlists/94020775335104: The connection is closed
```
About the org.gnome.Rhythmbox3 Flatpak installed:
```
$ flatpak info org.gnome.Rhythmbox3

Rhythmbox - Play and organize your music collection

          ID: org.gnome.Rhythmbox3
         Ref: app/org.gnome.Rhythmbox3/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 3.4.4
     License: GPL-2.0+ and GFDL-1.3
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 14,3 MB
     Runtime: org.gnome.Platform/x86_64/3.34
         Sdk: org.gnome.Sdk/x86_64/3.34

      Commit: b8251f26c397793a40fc519a55e9d6ac05e518584039ce1f25e93a3f38e796f7
      Parent: d27de23cc70a75b5416855179f02c4572dfecec8b245c0c2ff0e4efb7754b65a
     Subject: Update to 3.4.4 (de819454)
        Date: 2020-01-05 23:29:21 +0000
```

**Comment by hadess** [comment]
I'd need a backtrace from the crash. This is usually done using `flatpak-coredumpctl`:
`flatpak-coredumpctl org.gnome.Rhythmbox3`.

You run:
```
$ flatpak run org.gnome.Rhythmbox3 -d
```
you should also get more debug output, a copy of the file that causes the UTF-8 warnings would be appreciated.

**Comment by felipehw** [comment]
The file `2.zip` contents the output of: `$ flatpak run org.gnome.Rhythmbox3 -d 2>2.txt`

[2.zip](https://github.com/flathub/org.gnome.Rhythmbox3/files/4205767/2.zip)

**Comment by hadess** [comment]
Looks like your Marcel D2 and Grand Budapest Hotel files are broken.
`/mnt/home/home/dread/Music/marcelo d2/(2010) Canta Bezerra da Silva/14 Pai vÃ©io 171.mp3` and `/mnt/home/home/dread/Music/ost/(2014) The Grand Budapest Hotel - Wes Anderson/30 Alexandre Desplat - The Mystical Union.mp3`. Could you make those files available here? I'll delete them once I've downloaded them.

**Comment by felipehw** [comment]
Here are these two files ...
In my system I can reproduce them without problems.

~~[mp3s.zip](Removed)~~

**Comment by hadess** [comment]
Looks like it could actually be:
```
file:///mnt/home/home/dread/Music/ost/(2014)%20The%20Grand%20Budapest%20Hotel%20-%20Wes%20Anderson/31%20%D0%9E%D1%80%D0%BA%D0%B5%D1%81%D1%82%D1%80%20%D0%B8%D0%BC.%20%D0%9D.%D0%9F.%20%D0%9E%D1%81%D0%B8%D0%BF%D0%BE%D0%B2%D0%B0,%20%D0%92%D0%B8%D1%82%D0%B0%D0%BB%D0%B8%D0%B9%20%D0%94%D0%BC%D0%B8%D1%82%D1%80%D0%B8%D0%B5%D0%B2%D0%B8%D1%87%20%D0%93%D0%BD%D1%83%D1%82%D0%BE%D0%B2%20-%20Kamarinskaya.mp3
```
that's causing the problem. It's sufficiently broken that the system thinks it's UTF-8, but D-Bus doesn't think so and disconnects us from D-Bus. Rhythmbox closes because D-Bus was removed.

**Comment by felipehw** [comment]
I removed the file `31 Оркестр им. Н.П. Осипова, Виталий Дмитриевич Гнутов - Kamarinskaya.mp3` but the crash still happens.
Maybe the crash happens due to another reason. The log file is shorter and the crash gets less time to happen.

I'm sending to you the file `31 Оркестр им. Н.П. Осипова, Виталий Дмитриевич Гнутов - Kamarinskaya.mp3` and the new output of the crash.
Ah, these crashes didn't occur in the "normal" Rhythmbox.

~~[files.zip](Removed)~~

**Comment by hadess** [comment]
>  Maybe the crash happens due to another reason. The log file is shorter and the crash gets less time to happen.

Yes, this time it seems to be caused by:
```
file:///mnt/home/home/dread/Music/ost/Yu%20Yu%20Hakusho/(1997)%20%E5%B9%BD%E9%81%8A%E7%99%BD%E6%9B%B8%20%E3%82%AA%E3%83%AA%E3%82%B8%E3%83%8A%E3%83%AB%E3%83%BB%E3%82%B5%E3%82%A6%E3%83%B3%E3%83%89%E3%83%88%E3%83%A9%E3%83%83%E3%82%AF%20Vol.%202%20%E3%80%9C%E9%AD%94%E7%95%8C%E3%81%AE%E6%89%89%E7%B7%A8%E3%80%9C/04%20%E6%9C%AC%E9%96%93%E5%8B%87%E8%BC%94%20-%20%E8%A8%B1%E3%81%9B%E3%81%AD%E3%82%A7!.ogg
```

What's the output of `flatpak run -d --command="locale" org.gnome.Rhythmbox3` on your system?
Can you also try, afterwards, disabling the "MediaServer2" plugin in the preferences?

**Comment by felipehw** [comment]
Removing the *MediaServer2* plugin solved the problem!
Incredible. I'll leave this disabled. :)

But ... how the people are suposed to know this :/

Is there something that I can do to help with this ... ?

```
$ flatpak run -d --command="locale" org.gnome.Rhythmbox3
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=pt_BR.UTF-8
LC_TIME=pt_BR.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=pt_BR.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=pt_BR.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=pt_BR.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by hadess** [comment]
> Removing the _MediaServer2_ plugin solved the problem!

That's what was causing the crash, it's not a fix...

**Comment by hadess** [comment]
Could you please make your `~/.var/app/org.gnome.Rhythmbox3/data/rhythmbox/rhythmdb.xml` file available via email?

I think that the first problem is that because UTF-8 support isn't enabled in the metadata scanner, garbage got into the database. Then, on every startup, the garbage would be exported through the MediaServer, which would try to spew non-UTF-8 as D-Bus path, get disconnected from the D-Bus and close down because D-Bus connectivity is a requirement.

**Comment by hadess** [comment]
The filenames might also have had something to do with all that, I don't think the filenames/paths are valid UTF-8.

**Comment by felipehw** [comment]
These filenames are product of rename function of MusicBrainz Picard.
Could you give an e-mail to send the file?
Ps: There is some privacy concerns about this file (like logins of last.fm, etc.)?

**Comment by hadess** [comment]
> Could you give an e-mail to send the file?

`<masked>`

> Ps: There is some privacy concerns about this file (like logins of last.fm, etc.)?

Apart from the files in your database, no, there's no other information there.

**Comment by felipehw** [comment]
Sent!

**Comment by hadess** [comment]
I can't really find a way that this problem could happen. Which version of Flatpak are you using? And can you please double-check that you have the latest version of Flatpak and that `flatpak update` is all done?

**Comment by felipehw** [comment]
I have a recent version ... of everything for a Fedora 31 machine.

I'll leave my house now. We have carnival at Brazil :P
But, when I back ... I send to you anything that you need at this problem.

```
$ flatpak --version
Flatpak 1.4.3
$ flatpak update -y
Looking for updates…
Nothing to do.
$ 
```

**Comment by hadess** [comment]
> We have carnival at Brazil :P

Sei ;)

**Comment by Seqularise** [comment]
So, i have this problem and i`m ready to provide any needed info, just tell what logs and/or outputs you need

**Comment by hadess** [comment]
I need a backtrace of the crash, or a sure fire way to reproduce it. Right now, I can't reproduce it even with the information provided.

**Comment by hadess** [comment]
It's been more than 6 months. Please file a new bug with the backtrace of the crash if it still happens.
