### ISSUE TITLE
Keep flathub version more updated

### ISSUE THREAD

**Issue by crvigh** [flathub/org.gnome.Rhythmbox3#32]
Just a thought.

Why not keep the flathub rhythmbox version updated with the latest git changes, than limiting to the last release tag. Lots of fixes have gone into git after 3.4.4 release, and flathub could be a good place for users to try out and test the latest changes.

**Comment by hadess** [comment]
Making new releases would certainly help make this process easier, as appdata updates would make the list of changes easily accessible to users.

**Comment by crvigh** [comment]
Agree. That's the reason for https://gitlab.gnome.org/GNOME/rhythmbox/-/merge_requests/81

Forgot to close this issue.

Thanks
