### ISSUE TITLE
Update rhythmbox flatpak commit to recent version with podcast fixes

### ISSUE THREAD

**Issue by crvigh** [flathub/org.gnome.Rhythmbox3#39]
Refer https://github.com/flathub/org.gnome.Rhythmbox3/commit/08c5ac609bd808ce813ac975bb2e992771a483b8 for some history on this bug.

**Comment by crvigh** [comment]
Probably a version bump from `3.4.4` to `3.4.4.1` ?

**Comment by hadess** [comment]
Fixed in #46
