### ISSUE TITLE
Discovery and broadcast of DAAP is disabled due to no MDNS service

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.gnome.Rhythmbox3#4]
Connecting to a DAAP share was added https://github.com/flathub/org.gnome.Rhythmbox3/issues/1, however auto discovery and broadcast was disabled due to not being able to start/have an existing MDNS service running https://github.com/flatpak/flatpak/issues/348.

For now the preferences ui has been patched out of the DAAP plugin https://github.com/flathub/org.gnome.Rhythmbox3/blob/master/disable-daap-preferences.patch, so that the user can only perform "Connect to DAAP share" and then type the IP address.

From the disabled preferences menu,
If you tried to enable "Look for touch remotes" you get
```
(rhythmbox:2): libdmapsharing-WARNING **: Unable to start Remote lookup: MDNS service is not running
```
If you tried to enable "Share my music" you get
```
(rhythmbox:2): libdmapsharing-WARNING **: Unable to notify network of media sharing: The avahi MDNS service is not running
```

This issue tracks that these features have been disabled until MDNS works within flatpak.

**Comment by nedrichards** [comment]
Teleport appears to be able to discover and communicate with other peers on the same network (just tested here) and that uses Avahi I believe. https://github.com/flathub/com.frac_tion.teleport maybe test that?

**Comment by ahayzen** [comment]
@nedrichards ah interesting thanks, I'll take a look over the weekend see if I can figure it out. Maybe it just needs something like `"--system-talk-name=org.freedesktop.Avahi",`, but is that assuming that Avahi is on the host ?

**Comment by nedrichards** [comment]
I suspect it is. Obviously you'd prefer not to make that assumption but for
a lot of Linux systems it's a fair one to make right now.
