### ISSUE TITLE
Unable to use podcasts

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.gnome.Rhythmbox3#5]
Existing podcats cannot be refreshed (just a warning symbol)

Cannot add new podcast, when you first subscribe it says "Unable to load the feed. Check your network connection.". Sometimes another dialog pops up saying "There was a problem adding this podcast: Unable to parse the feed contents. Please verify the URL: https://itunespodcasturl"

![screenshot from 2018-02-15 17-49-28](https://user-images.githubusercontent.com/3669750/36285532-dc90250a-12a3-11e8-9143-a571a340717c.png)

It doesn't seem to be a general network permission issue, as it is able to search for the podcasts. I suspect it is missing a dependency to parse/determine the format of the resultant podcast URL.

I've been unsuccessful in trying to find debug messages for this, I'll see if I can determine any missing packages etc.

**Comment by ahayzen** [comment]
I tried adding libxml2 (before totem-pl-parser) and json-glib (before rhythmbox) but this didn't help.

The error itself seems to be coming from
https://github.com/GNOME/rhythmbox/blob/master/podcast/rb-podcast-parse.c#L223
https://github.com/GNOME/rhythmbox/blob/master/podcast/rb-podcast-manager.c#L2240

Totem-pl-parser - https://github.com/GNOME/totem-pl-parser - has the following dependencies
glib >= 2.36
gmime >= 2.6 or >= 3.0
libxml2
libquvi >= 0.9.1 (optional)
libarchive >= 3.0 (optional)
libgcrypt (optional)

I wonder if one of the optional depends can help here ? It appears that the itunes sources are just an XML document.

**Comment by hadess** [comment]
Fixed in https://github.com/flathub/org.gnome.Rhythmbox3/commit/a1a94287c17c00027ca100d30a542b530b675c2b
so should be fixed in tomorrow's Rhythmbox!
