### ISSUE TITLE
Locale not installed 

### ISSUE THREAD

**Issue by mbousq** [flathub/org.gnome.Rhythmbox3#53]
Hi. I have both en and fr locales installed on my system but when I start the app the language is set to English instead of French.

Looking at  /var/lib/flatpak/app/org.gnome.Rhythmbox3/x86_64/stable/some_UUID/files/share/locale/ 
the french locale is not installed.

`Flatpak config` returns:
```
languages: *unset* (default: en;fr)
extra-languages: *unset*
```

Not sure if this could be a flatpak bug instead ... I am using Ubuntu 22.04 and Flatpak 1.12.7

**Comment by hadess** [comment]
Running `flatpak update` should install the `fr` locale if Rhythmbox is already installed.

Check with `flatpak info org.gnome.Rhythmbox3.Locale` which "subdirectory" it lists.

**Comment by mbousq** [comment]
`flatpak info org.gnome.Rhythmbox3.Locale`
```
            ID: org.gnome.Rhythmbox3.Locale
           Ref: runtime/org.gnome.Rhythmbox3.Locale/x86_64/stable
          Arch: x86_64
        Branch: stable
        Origin: flathub
    Collection: org.flathub.Stable
  Installation: system
     Installed: 115,2 kB

        Commit: 22586738a1150cb37c580a1ad9d85ef5248ff91a2a4f3908a197d422ec84b1bd
        Parent: 9bfc5512294634881e40d44e44aaa73b7d8756789f1974f6ae64889b5044abaa
       Subject: Update rhythmbox to latest release (ba0aab19)
          Date: 2022-05-03 10:43:11 +0000
Subdirectories: /en,/fr
```

Having said that, in  /var/lib/flatpak/app/org.gnome.Rhythmbox3/x86_64/stable/some_UUID/files/share/locale/ the fr symlink redirects to 
/var/lib/flatpak/runtime/org.gnome.Rhythmbox3.Locale/x86_64/stable/some_UUID-en-fr/files/fr/share/fr/

whereas the translation file is in 

/var/lib/flatpak/runtime/org.gnome.Rhythmbox3.Locale/x86_64/stable/some_UUID-en-fr/files/fr/share/fr/LC_MESSAGES/rhythmbox.mo

Therefore the symlink is invalid

**Comment by hadess** [comment]
> Therefore the symlink is invalid

The symlinks are resolved *inside* the sandbox. So `flatpak run --command=ls org.gnome.Rhythmbox3 /app/share/locale/fr` if you want to try and resolve it. I'll close this, as this isn't a Rhythmbox Flathub bug. In fact, I'm not even sure there's a bug here.

**Comment by mbousq** [comment]
flatpak run  --env=LC_MESSAGES=fr_FR.UTF-8 org.gnome.Rhythmbox3 still starts in English without throwing any errors. Very weird as my other flatpaks are correctly translated

**Comment by hadess** [comment]
The symptoms existed even if the original analysis was wrong.

The translations not working was an upstream bug:
https://gitlab.gnome.org/GNOME/rhythmbox/-/merge_requests/152

Fix will be available in https://github.com/flathub/org.gnome.Rhythmbox3/pull/52 and in Flathub soon

**Comment by mbousq** [comment]
Thx !
