### ISSUE TITLE
Media keys don't work

### ISSUE THREAD

**Issue by ahayzen** [flathub/org.gnome.Rhythmbox3#6]
I see the following warning on startup
```
(rhythmbox:2): Rhythmbox-WARNING **: Unable to grab media player keys: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: org.freedesktop.DBus.Error.ServiceUnknown
```

Rhythmbox integrated with the MPRIS interface and this works correct, but the media keys fail to work so one can not pause/resume next/previous with keyboard media keys :-/

There is an entry in the finish-args that claims to be for the media-keys
```
/* media keys */
"--talk-name=org.gnome.SettingsDaemon.MediaKeys",
```

**Comment by TingPing** [comment]
This patch needs to be backported it seems: https://github.com/GNOME/rhythmbox/commit/a48c08641c2fb282fad21ff8b0f3e47932f0a656

**Comment by ahayzen** [comment]
@TingPing cool thanks, if no one else does, I'll try backporting the patch over the weekend and see if it works.
