### ISSUE TITLE
Consider upgrading runtime org.gnome.Platform version

### ISSUE THREAD

**Issue by karuboniru** [flathub/org.gnome.Rhythmbox3#60]
```
Info: runtime org.gnome.Platform branch 42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
```
Changing following line should be just enough.
https://github.com/flathub/org.gnome.Rhythmbox3/blob/8fc7d9b86fcd57690b5da16c55d690698c4f6224/org.gnome.Rhythmbox3.json#L4

**Comment by bbhtt** [comment]
[Depends on libsoup-2.4](https://gitlab.gnome.org/GNOME/rhythmbox/-/blob/ec823003cfc2ca1397fae432832b47a0cb762ba8/meson.build#L66), cannot bump to runtime 44 as it comes with libsoup3 only.

**Comment by hadess** [comment]
Fixed in https://github.com/flathub/org.gnome.Rhythmbox3/pull/62
