### ISSUE TITLE
Ampache plugin

### ISSUE THREAD

**Issue by lachmanfrantisek** [flathub/org.gnome.Rhythmbox3#9]
Hi,

is it possible to add (or somehow enable) the ampache plugin?

Thank you in advance!

**Comment by jmatthew** [comment]
It's not going to be included in the flatpak build, but you should be able to install the plugin in your home directory.

**Comment by lachmanfrantisek** [comment]
@jmatthew Thank you for the reply.

Do you know, what needs to be done for this? I don't know, what I am doing wrong:

- plugin location: `~/.local/share/rhythmbox/plugins/`
- `git clone https://github.com/lotan/rhythmbox-ampache.git`
- Any changes on the flatpak side? (Even `--filesystem=home` didn't work..)

Thank you!

**Comment by lachmanfrantisek** [comment]
@jmatthew  what about flatpak-plugin system?

(https://tingping.github.io/2018/03/18/flatpaking-plugins.html)
